spring.application.name=BakerySystem

# Database connection
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate auto DDL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



# Server port
server.port=8098

#upload-file
path-upload=./src/main/resources/uploads
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=30MB
spring.web.resources.static-locations=file:uploads/


# ===== Swagger / OpenAPI =====
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Sort cho g?n
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Enable (d�ng ?? t?t m? theo env)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

job.calculate.cron=0 0 0 * * ?
request.default=10

jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC
app.time.zone=Asia/Ho_Chi_Minh

app.idCake=1,2,3,4